DATA:
  DATASET: cub200-2011
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window7_224_1ktocub200_finetune
  DROP_PATH_RATE: 0.2
  SOURCE_NUM_CLASSES: 1000
  NUM_CLASSES: 200
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 10
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
SAVE_FREQ: 50